language: python

cache:
  directories:
  $HOME/.m2/repository
  $HOME/.sonar/cache
  $HOME/.gradle
  .gradle
addons:
  sonarcloud:
    organization: lruizarc-github
    token:
      secure:23dce1922f7ec756939755578397f9429470b04d
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

node_js:
  - "node"

addons:
  sonarcloud:
    organization: lruizarc-github
    token:
      secure:23dce1922f7ec756939755578397f9429470b04d
before_install:
  - pip install -U tox tox-travis
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
<<<<<<< HEAD
  - .travis/run.sh
=======
  - .travis/run.sh

cache:
  directories:
  $HOME/.m2/repository
  $HOME/.sonar/cache
  $HOME/.gradle
  .gradle
>>>>>>> bd6ad0cc6e546c231c5a4df8b619af444dbfc08a
