sudo: required

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

node_js:
  - "node"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - python3
      - python3-pip
      - curl

before_install:
  - sudo pip3 install coveralls tox-travis
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - bash .travis/install.sh

script:
  - bash .travis/run.sh
