version: '3'
services:
  web:
    build: ./smoke-scripts
    entrypoint:
      - bash
      - -l
      - /smoke/run.sh
    volumes:
      - ${PWD}/smoke-editor:/smoke
    ports:
      - "8080:8080"
    tty: true
  backend:
    build: ./smoke-scripts
    entrypoint:
      - bash
      - -l
      - /smoke/run.sh
    volumes:
      - ${PWD}/smoke-backend:/smoke
    ports:
      - "8000:8000"
    tty: true
